#35- updated the pull request workflow file

diff --git a/.github/workflows/firebase-hosting-pull-request.yml b/.github/workflows/firebase-hosting-pull-request.yml
--- a/.github/workflows/firebase-hosting-pull-request.yml
+++ b/.github/workflows/firebase-hosting-pull-request.yml
@@ -27,6 +27,10 @@ jobs:
           echo PUBLIC_FIREBASE_MESSENGER_ID="${{ secrets.PUBLIC_FIREBASE_MESSENGER_ID_MVP }}" >> .env
           echo PUBLIC_FIREBASE_APP_ID="${{ secrets.PUBLIC_FIREBASE_APP_ID_MVP }}" >> .env
           echo PUBLIC_FIREBASE_MEASUREMENT_ID="${{ secrets.PUBLIC_FIREBASE_MEASUREMENT_ID_MVP }}" >> .env
+
+      - name: Validate serviceAccountKey secret
+        run: |
+          echo "${{ secrets.FIREBASE_SERVICEACCOUNT_KEY_MVP }}" | base64 -d || echo "Invalid base64 input"
       - name: Create serviceAccountKey.json
         run: echo "${{ secrets.FIREBASE_SERVICEACCOUNT_KEY_MVP }}" | base64 -d > src/serviceAccountKey.json
       - uses: FirebaseExtended/action-hosting-deploy@v0
